server:
   port: 6464
spring:
  datasource:
    url: jdbc:oracle:thin:@10.90.1.107:1521/SIT
    username: HR
    password: HR
    
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true